FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /APP
COPY ./publish .
ENV aspnetcore_urls http://*:5000
ENV ASPNETCORE_ENVIRONMENT docker
EXPOSE 5000
ENTRYPOINT dotnet ProductService.dll
           