FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /APP
COPY ./publish .
ENV aspnetcore_urls http://*:5002
ENV ASPNETCORE_ENVIRONMENT docker
EXPOSE 5002
ENTRYPOINT dotnet OrderService.dll
           